### ISSUE TITLE
The TAT and the person who entered the test are not shown

### ISSUE THREAD

**Issue by mapesa** [ilabafrica/blis-kenya#21]
On sanitas,  turnaround time and the person who entered a test are not shown for test results submitted from BLIS.

**Comment by kitsao** [comment]
I'll communicate to Kibwage tomorrow on how he'll be able to get these
details to the Sanitas end.

**Comment by mapesa** [comment]
Please tell him about issue #4 as well. Its about relaying verification info to Sanitas
