### ISSUE TITLE
Show unpaid for requests in BLIS

### ISSUE THREAD

**Issue by mapesa** [ilabafrica/blis-kenya#9]
Show tests requested but with pending payments. Users should be able to see these requests but not act on them (At the moment, the lab staff often switch back to Sanitas to check if a patient has paid).

**Comment by kitsao** [comment]
I thought tests that have been paid for only will appear on BLIS.

**Comment by mapesa** [comment]
True. Only tests that have been paid for should appear. But consider what's happening on the ground:
1. A patient comes to the lab with his card
2. The lab staff keys in the visit number in BLIS and gets a blank.

In this case its not clear why BLIS doesn't have any data for the patient. What has been happening is that the technicians switch to Sanitas where the patient data is displayed, and they can then tell the reason for the failure.

One of the technicians suggested that we show this data in BLIS. We could add another status like "NOT PAID" and disable all actions on these records.

**Comment by kitsao** [comment]
Ok. I get it.
